import React, { useState, useEffect } from 'react';
import { generateVerseSummary } from '../services/geminiService';
import SparklesIcon from './icons/SparklesIcon';

interface VerseSummaryModalProps {
  verseText: string;
  reference: string;
  onClose: () => void;
}

const VerseSummaryModal: React.FC<VerseSummaryModalProps> = ({ verseText, reference, onClose }) => {
  const [summary, setSummary] = useState('');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchSummary = async () => {
        setIsLoading(true);
        const result = await generateVerseSummary(verseText, reference);
        setSummary(result);
        setIsLoading(false);
    };
    fetchSummary();
  }, [verseText, reference]);

  return (
    <div 
      className="fixed inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center z-50 p-4 animate-fadeInUp"
      onClick={onClose}
    >
      <div 
        className="bg-slate-900 border border-slate-700 rounded-xl shadow-2xl w-full max-w-lg p-6 relative"
        onClick={(e) => e.stopPropagation()}
      >
        <button onClick={onClose} className="absolute top-4 right-4 text-slate-400 hover:text-white">&times;</button>
        
        <div className="flex items-center mb-6">
            <div className="p-2 bg-amber-500/10 rounded-lg text-amber-400 mr-3">
                <SparklesIcon className="h-6 w-6" />
            </div>
            <h2 className="text-xl font-serif font-bold text-white">AI Insight: {reference}</h2>
        </div>

        {isLoading ? (
             <div className="flex flex-col items-center justify-center py-8">
                <div className="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-amber-500 mb-4"></div>
                <p className="text-slate-400 text-sm animate-pulse">Analyzing scripture...</p>
             </div>
        ) : (
            <div className="space-y-4">
                <p className="text-slate-300 leading-relaxed text-lg">
                    {summary}
                </p>
                <div className="pt-4 border-t border-slate-800 text-xs text-slate-500 text-center">
                    Generated by AI. Use for quick understanding.
                </div>
            </div>
        )}
        
        <div className="mt-6 flex justify-end">
            <button
                onClick={onClose}
                className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white font-bold rounded-lg transition-colors"
            >
                Close
            </button>
        </div>
      </div>
    </div>
  );
};

export default VerseSummaryModal;