
import React, { useState, useEffect } from 'react';
import { generateVerseSummary } from '../services/geminiService';
import SparklesIcon from './icons/SparklesIcon';
import XIcon from './icons/XIcon';

interface VerseSummaryModalProps {
  verseText: string;
  reference: string;
  language: string;
  onClose: () => void;
  position?: 'top' | 'bottom';
}

const VerseSummaryModal: React.FC<VerseSummaryModalProps> = ({ verseText, reference, language, onClose, position = 'top' }) => {
  const [data, setData] = useState<{ key_word: string, summary: string } | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    let isMounted = true;
    const fetchSummary = async () => {
        setIsLoading(true);
        try {
            const result = await generateVerseSummary(verseText, reference, language);
            if (isMounted) setData(result);
        } catch (e) {
            console.error(e);
        } finally {
            if (isMounted) setIsLoading(false);
        }
    };
    fetchSummary();
    return () => { isMounted = false; };
  }, [verseText, reference, language]);

  const positionClasses = position === 'top'
    ? 'bottom-[calc(100%+16px)] origin-bottom'
    : 'top-[calc(100%+16px)] origin-top';

  return (
    <div 
      className={`absolute left-1/2 -translate-x-1/2 ${positionClasses} w-[85vw] max-w-sm bg-slate-900/95 backdrop-blur-xl border border-slate-700/50 rounded-2xl shadow-2xl z-50 p-5 pointer-events-auto animate-fadeInUp cursor-default`}
      onClick={(e) => e.stopPropagation()}
    >
        <div className="flex justify-between items-start mb-3">
            <div className="flex items-center">
                <div className="p-1.5 bg-amber-500/10 rounded-lg text-amber-400 mr-2">
                    <SparklesIcon className="h-4 w-4" />
                </div>
                <h2 className="text-sm font-bold font-serif text-slate-200">AI Insight: {reference}</h2>
            </div>
            <button onClick={onClose} className="text-slate-500 hover:text-white transition-colors p-1 -mr-2 -mt-2">
                <XIcon className="h-4 w-4" />
            </button>
        </div>

        {isLoading ? (
             <div className="flex flex-col items-center justify-center py-6 space-y-3">
                <div className="animate-spin rounded-full h-6 w-6 border-2 border-amber-500 border-t-transparent"></div>
                <p className="text-xs text-slate-500 font-medium animate-pulse">Analyzing scripture...</p>
             </div>
        ) : data ? (
            <div className="space-y-4">
                <div className="flex justify-center">
                    <div className="inline-flex flex-col items-center">
                        <span className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-1">Key Takeaway</span>
                        <span className="px-4 py-1.5 bg-gradient-to-r from-amber-500/20 to-amber-600/20 text-amber-300 border border-amber-500/30 rounded-full text-sm font-bold shadow-[0_0_10px_rgba(245,158,11,0.1)]">
                            {data.key_word}
                        </span>
                    </div>
                </div>
                <p className="text-slate-300 text-sm leading-relaxed text-center">
                    {data.summary}
                </p>
                <div className="pt-3 border-t border-slate-800/50 flex justify-between items-center">
                    <span className="text-[10px] text-slate-600 uppercase tracking-wider font-bold">Generated by AI</span>
                </div>
            </div>
        ) : (
             <div className="text-center py-4">
                <p className="text-red-400 text-xs">Insight unavailable.</p>
             </div>
        )}
    </div>
  );
};

export default VerseSummaryModal;
